### ISSUE TITLE
Error upon startup

### ISSUE THREAD

**Issue by OmegaShaman** [nikosgram13/Gringotts#106]
**Describe the bug**
Weird error message I get on startup

**To Reproduce**
1. Put in Gringotts jar
2. Load server

**Expected behavior**
Should load the plugin.

**Screenshots**
`[18:17:05 WARN]: Legacy plugin Reserve v0.1.3 does not specify an api-version.
[18:17:05 ERROR]: [com.avaje.ebean.config.PropertyMapLoader] ebean.properties not found
[18:17:05 INFO]: [com.avaje.ebeaninternal.server.lib.sql.DataSourcePool] DataSourcePool [Gringotts] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
[18:17:05 INFO]: [com.avaje.ebeaninternal.server.subclass.SubClassManager] SubClassFactory parent ClassLoader [org.bukkit.plugin.java.PluginClassLoader]
[18:17:06 ERROR]: [com.avaje.ebeaninternal.server.subclass.SubClassFactory] Error creating subclass for [org.gestern.gringotts.data.EBeanAccount]
java.lang.ArrayIndexOutOfBoundsException: Index 9322 out of bounds for length 74
        at com.avaje.ebean.enhance.asm.ClassReader.readClass(ClassReader.java:1976) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:464) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:420) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassFactory.subclassBytes(SubClassFactory.java:123) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassFactory.create(SubClassFactory.java:83) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassManager.createClass(SubClassManager.java:113) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassManager.resolve(SubClassManager.java:100) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkSubclass(BeanDescriptorManager.java:1522) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1469) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1157) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1077) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:584) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:271) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:143) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:209) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[gringotts-2.12.3.jar:?]
        at org.gestern.gringotts.Gringotts.<init>(Gringotts.java:97) ~[gringotts-2.12.3.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:85) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:417) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:325) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:453) ~[purpur-1.19.2.jar:git-Purpur-1775]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:314) ~[purpur-1.19.2.jar:git-Purpur-1775]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1775]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1775]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:17:06 ERROR]: [com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager] Error in deployment
javax.persistence.PersistenceException: Error creating subclass for [org.gestern.gringotts.data.EBeanAccount]
        at com.avaje.ebeaninternal.server.subclass.SubClassManager.createClass(SubClassManager.java:117) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassManager.resolve(SubClassManager.java:100) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkSubclass(BeanDescriptorManager.java:1522) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1469) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1157) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1077) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:584) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:271) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:143) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:209) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[gringotts-2.12.3.jar:?]
        at org.gestern.gringotts.Gringotts.<init>(Gringotts.java:97) ~[gringotts-2.12.3.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:85) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:417) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:325) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:453) ~[purpur-1.19.2.jar:git-Purpur-1775]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:314) ~[purpur-1.19.2.jar:git-Purpur-1775]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1775]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1775]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 9322 out of bounds for length 74
        at com.avaje.ebeaninternal.server.subclass.SubClassFactory.create(SubClassFactory.java:96) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassManager.createClass(SubClassManager.java:113) ~[gringotts-2.12.3.jar:?]
        ... 28 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 9322 out of bounds for length 74
        at com.avaje.ebean.enhance.asm.ClassReader.readClass(ClassReader.java:1976) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:464) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:420) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassFactory.subclassBytes(SubClassFactory.java:123) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassFactory.create(SubClassFactory.java:83) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassManager.createClass(SubClassManager.java:113) ~[gringotts-2.12.3.jar:?]
        ... 28 more
[18:17:06 ERROR]: Could not load 'plugins/gringotts-2.12.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: javax.persistence.PersistenceException: Error creating subclass for [org.gestern.gringotts.data.EBeanAccount]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:417) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:325) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:453) ~[purpur-1.19.2.jar:git-Purpur-1775]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:314) ~[purpur-1.19.2.jar:git-Purpur-1775]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1775]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1775]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: javax.persistence.PersistenceException: Error creating subclass for [org.gestern.gringotts.data.EBeanAccount]
        at com.avaje.ebeaninternal.server.subclass.SubClassManager.createClass(SubClassManager.java:117) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassManager.resolve(SubClassManager.java:100) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkSubclass(BeanDescriptorManager.java:1522) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1469) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1157) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1077) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:584) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:271) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:143) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:209) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[gringotts-2.12.3.jar:?]
        at org.gestern.gringotts.Gringotts.<init>(Gringotts.java:97) ~[gringotts-2.12.3.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:85) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 7 more
Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 9322 out of bounds for length 74
        at com.avaje.ebeaninternal.server.subclass.SubClassFactory.create(SubClassFactory.java:96) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassManager.createClass(SubClassManager.java:113) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassManager.resolve(SubClassManager.java:100) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkSubclass(BeanDescriptorManager.java:1522) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1469) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1157) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1077) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:584) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:271) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:143) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:209) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[gringotts-2.12.3.jar:?]
        at org.gestern.gringotts.Gringotts.<init>(Gringotts.java:97) ~[gringotts-2.12.3.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:85) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 7 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 9322 out of bounds for length 74
        at com.avaje.ebean.enhance.asm.ClassReader.readClass(ClassReader.java:1976) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:464) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:420) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassFactory.subclassBytes(SubClassFactory.java:123) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassFactory.create(SubClassFactory.java:83) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassManager.createClass(SubClassManager.java:113) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.subclass.SubClassManager.resolve(SubClassManager.java:100) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkSubclass(BeanDescriptorManager.java:1522) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1469) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1157) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1077) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:584) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:271) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:143) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:209) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[gringotts-2.12.3.jar:?]
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[gringotts-2.12.3.jar:?]
        at org.gestern.gringotts.Gringotts.<init>(Gringotts.java:97) ~[gringotts-2.12.3.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:85) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 7 more`

**Desktop (please complete the following information):**
 - Server Type: Purpur
 - Server Version: 1.19.2-1775
 - Gringotts Version: 2.12.3

**Additional context**

**Comment by nikosgram** [comment]
Duplicated: https://github.com/nikosgram/gringotts/issues/104
