### ISSUE TITLE
Bug or not?

### ISSUE THREAD

**Issue by rackgaming** [nikosgram13/Gringotts#125]
**Describe the bug**
Gringotts config YML is not taken into consideration on reload or restart on 1.19, I am using the %vault_eco% placeholders as intended.

**To Reproduce**
1. Combine all plugins AnimatedScoreboard, Vault, mobhunting, levelledmobs, ect and then try to create a vault chest.
**Expected behavior**
I expected it to separate the inventory and ignore what's in the inventory and only show what's in the chest and I am using luckperms.
**Screenshots**
![image](https://user-images.githubusercontent.com/7550358/197403265-11c4d9dc-bff0-4d44-965f-ecb70ecc2f64.png)
![image](https://user-images.githubusercontent.com/7550358/197403273-f18e6771-a5f7-4d38-a0d4-3f6cadd760ab.png)

**Desktop (please complete the following information):**
Server Type: Paper MC 1.19
Gringotts Version: 2.12.4
Vault Version: 1.7.3
MobHunting version: MobHunting 8.1.8
I also use LevelledMobs and animated scoreboard as well as GriefPrevention

**Additional context**
I don't really know if this is a bug or not, for some reason vault is not loading just the vault side but loads the vault balance placeholders.

**Comment by rackgaming** [comment]
also here is a list of all my plugins 
![image](https://user-images.githubusercontent.com/7550358/197404258-2b4567e1-c563-4a6e-9721-171e42dd2217.png)

**Comment by rackgaming** [comment]
another thing to note: it worked fine on realscoreboard but for some reason does not work on this one but realscoreboard would output an error.

**Comment by nikosgram** [comment]
Interesting. I'll have a look after I finish the performance improvement changes <3

**Comment by rackgaming** [comment]
Ya it just keeps messing with the vault api returning an error. Both scoreboards. It also happens when I become OP. Forgot to mention the servers arein offline mode due to minehuts velocity server

**Comment by rackgaming** [comment]
So the placeholderbreaking is another bug

**Comment by rackgaming** [comment]
`[16:41:46 WARN]: org.gestern.gringotts.GringottsException: java.util.concurrent.TimeoutException
[16:41:46 WARN]: 	at gringotts-2.12.4-SNAPSHOT.jar//org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:453)
[16:41:46 WARN]: 	at gringotts-2.12.4-SNAPSHOT.jar//org.gestern.gringotts.GringottsAccount.getBalance(GringottsAccount.java:81)
[16:41:46 WARN]: 	at gringotts-2.12.4-SNAPSHOT.jar//org.gestern.gringotts.api.impl.GringottsEco$ValidAccount.balance(GringottsEco.java:580)
[16:41:46 WARN]: 	at gringotts-2.12.4-SNAPSHOT.jar//org.gestern.gringotts.api.impl.VaultConnector.getBalance(VaultConnector.java:125)
[16:41:46 WARN]: 	at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:157)
[16:41:46 WARN]: 	at com.extendedclip.papi.expansion.vault.VaultEcoHook.onPlaceholderRequest(VaultEcoHook.java:100)
[16:41:46 WARN]: 	at com.extendedclip.papi.expansion.vault.VaultExpansion.onRequest(VaultExpansion.java:97)
[16:41:46 WARN]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[16:41:46 WARN]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[16:41:46 WARN]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[16:41:46 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.core.PlaceholderHandler.replacePlaceholderAPI(PlaceholderHandler.java:68)
[16:41:46 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.core.PlaceholderHandler.replaceBoth(PlaceholderHandler.java:62)
[16:41:46 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.core.PlaceholderHandler.replacePlaceholdersThrows(PlaceholderHandler.java:38)
[16:41:46 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.objects.PlayerScoreboardLine.update(PlayerScoreboardLine.java:126)
[16:41:46 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.objects.PlayerScoreboard.update(PlayerScoreboard.java:91)
[16:41:46 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.objects.ScoreboardPlayer.tickScoreboards(ScoreboardPlayer.java:448)
[16:41:46 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.core.PlayerScoreboardHandler.lambda$init$1(PlayerScoreboardHandler.java:196)
[16:41:46 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[16:41:46 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:41:46 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:41:46 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:41:46 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:41:46 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:41:46 WARN]: Caused by: java.util.concurrent.TimeoutException
[16:41:46 WARN]: 	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
[16:41:46 WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
[16:41:46 WARN]: 	at gringotts-2.12.4-SNAPSHOT.jar//org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:451)
[16:41:46 WARN]: 	... 22 more
[16:41:53 ERROR]: [AnimatedScoreboard] PlaceholderAPI caused an error while parsing line "&aCash: &f&l$%vault_eco_balance_fixed%" for dek9ning. This is not an issue with AnimatedScoreboard and should instead be fixed by the maintainer of the placeholder pack you are trying to use.
[16:41:53 WARN]: org.gestern.gringotts.GringottsException: java.util.concurrent.TimeoutException
[16:41:53 WARN]: 	at gringotts-2.12.4-SNAPSHOT.jar//org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:453)
[16:41:53 WARN]: 	at gringotts-2.12.4-SNAPSHOT.jar//org.gestern.gringotts.GringottsAccount.getBalance(GringottsAccount.java:81)
[16:41:53 WARN]: 	at gringotts-2.12.4-SNAPSHOT.jar//org.gestern.gringotts.api.impl.GringottsEco$ValidAccount.balance(GringottsEco.java:580)
[16:41:53 WARN]: 	at gringotts-2.12.4-SNAPSHOT.jar//org.gestern.gringotts.api.impl.VaultConnector.getBalance(VaultConnector.java:125)
[16:41:53 WARN]: 	at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:157)
[16:41:53 WARN]: 	at com.extendedclip.papi.expansion.vault.VaultEcoHook.onPlaceholderRequest(VaultEcoHook.java:100)
[16:41:53 WARN]: 	at com.extendedclip.papi.expansion.vault.VaultExpansion.onRequest(VaultExpansion.java:97)
[16:41:53 WARN]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[16:41:53 WARN]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[16:41:53 WARN]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[16:41:53 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.core.PlaceholderHandler.replacePlaceholderAPI(PlaceholderHandler.java:68)
[16:41:53 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.core.PlaceholderHandler.replaceBoth(PlaceholderHandler.java:62)
[16:41:53 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.core.PlaceholderHandler.replacePlaceholdersThrows(PlaceholderHandler.java:38)
[16:41:53 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.objects.PlayerScoreboardLine.update(PlayerScoreboardLine.java:126)
[16:41:53 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.objects.PlayerScoreboard.update(PlayerScoreboard.java:91)
[16:41:53 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.objects.ScoreboardPlayer.tickScoreboards(ScoreboardPlayer.java:448)
[16:41:53 WARN]: 	at AnimatedScoreboard.jar//me.jasperjh.animatedscoreboard.core.PlayerScoreboardHandler.lambda$init$1(PlayerScoreboardHandler.java:196)
[16:41:53 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[16:41:53 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:41:53 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:41:53 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:41:53 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:41:53 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:41:53 WARN]: Caused by: java.util.concurrent.TimeoutException
[16:41:53 WARN]: 	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
[16:41:53 WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
[16:41:53 WARN]: 	at gringotts-2.12.4-SNAPSHOT.jar//org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:451)
[16:41:53 WARN]: 	... 22 more` New Bug
