### ISSUE TITLE
Please advice valid gringotts version for mc 1.18.2 

### ISSUE THREAD

**Issue by koenigstag** [nikosgram13/Gringotts#147]
**Description**
After installing Gringotts on Spigot server 1.18.2 I receive server console errors, and cannot create `town vault`.
When using `gringotts` and `grongotts-towny` both version `2.12.4-SNAPSHOT` server console says: 
```sh
[Server thread/ERROR]: Could not load 'plugins\gringotts-towny-2.12.4-SNAPSHOT.jar' in folder 'plugins' 
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.19
at org.bukkit.craftbukkit.v1_18_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:317) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:407) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:232) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
```
But Towny says: 
```sh
[Server thread/INFO]: [Towny]   Economy: Gringotts via Vault
```
Must say that version 2.12.4-SNAPSHOT can create `player vault` from wooden chest. But when I create `town vault` - placed sign does not get triggered and does not applies town name, leaving it as a regular sign.

I assume that gringotts plugin loaded succesfully, but gringotts-towny plugin failed to boot and does not connect towny with gringotts.

What version of gringotts plugin can you advice for server 1.18.2 ?

**To Reproduce**
1. Install spigot-1.18.2-R0.1-SNAPSHOT server
2. Install Towny-0.99.1.0 and TownyChat-0.106 plugins
3. Install Vault plugin (version 1.7.3-b131)
4. Install Gringotts and Gringotts-Towny (2.12.4-SNAPSHOT)
5. Start the server
6. See errors on server console
7. Connect to server
8. Create new town
9. Create `town vault` inside `home` plot

**Expected behavior**
`gringotts-towny` version `2.12.4-SNAPSHOT` should work with Spigot 1.18.2-R0.1-SNAPSHOT and Towny 0.99.1.0. And should create `town vault`.

**Screenshots**
I can post screenshots later if it will be required during conversation.

**Versions:**
 - Server Type: Spigot
 - Server Version: spigot-1.18.2-R0.1-SNAPSHOT
 - Gringotts Version: 2.12.4-SNAPSHOT
 - Towny Advanced Version: 0.99.1.0
 - Vault plugin Version: 1.7.3-b131

**Comment by nikosgram** [comment]
I can see no reason for Gringotts and Gringotts Towny to not supporting 1.18.2, except of the additionally complexity of testing another version, that was the only consideration on my decision of dropping support for 1.18.2 and maintaining Gringotts only for 1.19.

If there is somebody that can provide help with testing 1.18.2, I'm more than happy to allow invest the time of supporting 1.18.2 again. :)

**Comment by koenigstag** [comment]
IMHO, I think that the latest most stable version of minecraft which has the most Forge and Fabric mods is 1.18.2.

So, can I help you with tests of 1.18.2 ?
How tests are going to happen ?

**Comment by nikosgram** [comment]
Is going to be incredible helpful to report any possible bugs for 1.18.2, that would be more than enough help tbh :) 

I'll let you know by the time I have an implementation in place.

**Comment by nikosgram** [comment]
Hello :) 

Version 2.12.5 should properly support 1.18.2

Feel free to give it a try from here -> https://github.com/nikosgram/gringotts/releases/tag/2.12.5
