### ISSUE TITLE
Cannot load gringotts plugin on Magma server core (NoClassDefFoundError PersistenceException)

### ISSUE THREAD

**Issue by koenigstag** [nikosgram13/Gringotts#151]
**Describe the bug**
On newly created server, with fresh installed plugins server console emits error when loading gringotts plugin:
```
[Server thread/ERROR] [Minecraft/]: Could not load 'plugins\gringotts-2.12.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: javax/persistence/PersistenceException
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:142) ~[forge-1.18.2-40.2.9-universal.jar%2358!/:?] {re:classloading}
        ...
Caused by: java.lang.NoClassDefFoundError: javax/persistence/PersistenceException
        at org.gestern.gringotts.Gringotts.<init>(Gringotts.java:97) ~[gringotts-2.12.5.jar:?] {}
        ...
Caused by: java.lang.ClassNotFoundException: javax.persistence.PersistenceException
        at org.magmafoundation.magma.remapping.loaders.RemappingURLClassLoader.findClass(RemappingURLClassLoader.java:96) ~[forge-1.18.2-40.2.9-universal.jar%2358!/:?] {re:classloading}
        ...
[Server thread/ERROR] [Minecraft/]: Could not load 'plugins\gringotts-towny-2.12.5.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency Gringotts. Please download and install Gringotts to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:268) ~[forge-1.18.2-40.2.9-universal.jar%2358!/:?] {re:classloading}
        ...
```

**To Reproduce**
Steps to reproduce:
1. Download and start Magma server. Accept EULA.
2. Restart server to create folders.
3. Place all plugins into folder
4. Restart server
5. See console error

**Expected behavior**
A Gringotts plugin to load correctly on server boot.

Versions:
Server Type: Magma-1.18.2-40.2.9-cd023882
Towny: 0.99.2.0
Vault: 1.7.3-b131
Gringotts: 2.12.5
Gringotts-towny: 2.12.5

**Screenshots**

**Comment by nikosgram** [comment]
Hello :) 

We currently have no intentions to extend support to other platforms besides Spigot and Paper, mainly because of the additional complexity that involves.
