### ISSUE TITLE
Cannot load gringotts plugin on CatServer server core (NoClassDefFoundError DatabasePlatform)

### ISSUE THREAD

**Issue by koenigstag** [nikosgram13/Gringotts#152]
**Describe the bug**
On newly created server, with fresh installed plugins server console emits error when loading gringotts plugin:
```
[Server thread/ERROR]: Could not load 'plugins\gringotts-2.12.5.jar' in folder 'plugins'
 org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/avaje/ebean/config/dbplatform/DatabasePlatform
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[forge-1.18.2-40.2.4-universal.jar%2360!/:?]
        ...
Caused by: java.lang.NoClassDefFoundError: com/avaje/ebean/config/dbplatform/DatabasePlatform
        at java.lang.Class.forName0(Native Method) ~[?:?]
        ...
Caused by: java.lang.ClassNotFoundException: com.avaje.ebean.config.dbplatform.DatabasePlatform
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:187) ~[forge-1.18.2-40.2.4-universal.jar%2360!/:?]
        ...
Caused by: java.lang.ClassNotFoundException: com.avaje.ebean.config.dbplatform.DatabasePlatform
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        ...
[Server thread/ERROR]: Could not load 'plugins\gringotts-towny-2.12.5.jar' in folder 'plugins'
 org.bukkit.plugin.UnknownDependencyException: Unknown dependency Gringotts. Please download and install Gringotts to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:268) ~[forge-1.18.2-40.2.4-universal.jar%2360!/:?]
        ...
[Server thread/ERROR]: Error occurred while enabling Vault v1.7.3-b131 (Is it up to date?)
 java.lang.NoClassDefFoundError: com/avaje/ebean/config/dbplatform/DatabasePlatform
        at java.lang.Class.forName0(Native Method) ~[?:?]
        ...
```

**To Reproduce**
1. Download and start CatServer server. Accept EULA.
2. Restart server to create folders.
3. Place all plugins into folder
4. Restart server
5. See console error

Versions:
Server Type: CatServer-1.18.2-6c3f5965
Towny: 0.99.2.0
Vault: 1.7.3-b131
Gringotts: 2.12.5
Gringotts-towny: 2.12.5

**Screenshots**

**Comment by nikosgram** [comment]
Hello :) 

We currently have no intentions to extend support to other platforms besides Spigot and Paper, mainly because of the additional complexity that involves.
