### ISSUE TITLE
On SignChangeEvent with non-null line(0) an Adventure error is thrown.

### ISSUE THREAD

**Issue by LlmDl** [nikosgram13/Gringotts#68]
Startup sections of Gringotts, Vault:
```
[15:51:16] [Server thread/INFO]: [Gringotts] Loading Gringotts v2.12.0
[15:51:16] [Server thread/INFO]: [Gringotts] Plugin Towny hooked.
[15:51:16] [Server thread/INFO]: [Gringotts] Plugin Vault hooked.
[15:51:16] [Server thread/WARN]: [Gringotts] Unable to hook plugin Reserve
[15:51:16] [Server thread/INFO]: [Gringotts] Loading dependency Towny
[15:51:16] [Server thread/INFO]: [Gringotts] Loading dependency Vault
[15:51:16] [Server thread/INFO]: [Gringotts] Enabling Gringotts v2.12.0
[15:51:16] [Server thread/INFO]: [Gringotts] Found Bukkit version: 1.16.5-R0.1-SNAPSHOT. All features enabled.
[15:51:16] [Server thread/INFO]: [Gringotts] Enabling dependency Towny
[15:51:16] [Server thread/INFO]: [Gringotts] Enabling dependency Vault
[15:51:16] [Server thread/INFO]: [Gringotts] Registered Vault interface.

[15:51:16] [Server thread/INFO]: [Vault] Enabling Vault v1.7.2-b107
[15:51:16] [Server thread/INFO]: [Vault] [Vault][Economy] Gringotts hooked.
[15:51:16] [Server thread/INFO]: [Vault] [Economy] Gringotts found: Loaded
```
Error thrown when any SignChangeEvent with a non-null line(0) is thrown ~~sign is placed on a chest with the first line `[town vault]`~~:

```
[15:54:00] [Server thread/ERROR]: Could not pass event SignChangeEvent to Gringotts v2.12.0
java.lang.NoClassDefFoundError: net/kyori/adventure/text/serializer/plain/PlainTextComponentSerializer
	at org.gestern.gringotts.event.AccountListener.onSignChange(AccountListener.java:43) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor4.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-776]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2984) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$19(PlayerConnection.java:2941) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$1(PlayerConnection.java:483) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$3(PlayerConnection.java:497) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-776]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by LlmDl** [comment]
Looks like Adventure isn't shaded into Gringotts.

**Comment by nikosgram** [comment]
Hello @LlmDl  :)

Can you try the latest release?

**Comment by LlmDl** [comment]
No bueno, Gringotts doesn't start:
```
[14:31:05] [Server thread/ERROR]: [org.gestern.gringotts.ebean.config.PropertyMapLoader] ebean.properties not found
[14:31:05] [Server thread/INFO]: [org.gestern.gringotts.ebeaninternal.server.lib.sql.DataSourcePool] DataSourcePool [Gringotts] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
[14:31:05] [Server thread/INFO]: [org.gestern.gringotts.ebeaninternal.server.subclass.SubClassManager] SubClassFactory parent ClassLoader [org.bukkit.plugin.java.PluginClassLoader]
[14:31:05] [Server thread/ERROR]: Could not load 'plugins\gringotts-2.12.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/avaje/ebean/bean/EntityBeanIntercept
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:353) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-776]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-776]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/avaje/ebean/bean/EntityBeanIntercept
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3305) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3510) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2691) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.reflect.EnhanceBeanReflect.defaultConstructor(EnhanceBeanReflect.java:67) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.reflect.EnhanceBeanReflect.<init>(EnhanceBeanReflect.java:43) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.reflect.EnhanceBeanReflectFactory.create(EnhanceBeanReflectFactory.java:10) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.deploy.BeanDescriptorManager.setBeanReflect(BeanDescriptorManager.java:1359) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1161) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1077) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:584) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:271) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:143) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:209) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[?:?]
	at org.gestern.gringotts.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[?:?]
	at org.gestern.gringotts.Gringotts.<init>(Gringotts.java:101) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350) ~[?:?]
	at java.lang.Class.newInstance(Class.java:642) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:94) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Paper-776]
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.avaje.ebean.bean.EntityBeanIntercept
	at java.lang.ClassLoader.findClass(ClassLoader.java:716) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3305) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3510) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2691) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.reflect.EnhanceBeanReflect.defaultConstructor(EnhanceBeanReflect.java:67) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.reflect.EnhanceBeanReflect.<init>(EnhanceBeanReflect.java:43) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.reflect.EnhanceBeanReflectFactory.create(EnhanceBeanReflectFactory.java:10) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.deploy.BeanDescriptorManager.setBeanReflect(BeanDescriptorManager.java:1359) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1161) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1077) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:584) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:271) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:143) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:209) ~[?:?]
	at org.gestern.gringotts.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[?:?]
	at org.gestern.gringotts.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[?:?]
	at org.gestern.gringotts.Gringotts.<init>(Gringotts.java:101) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350) ~[?:?]
	at java.lang.Class.newInstance(Class.java:642) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:94) ~[patched_1.16.5.jar:git-Paper-776]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Paper-776]
	... 7 more
```

**Comment by nikosgram** [comment]
Can you please try again? :) Latest version.

**Comment by nikosgram** [comment]
https://github.com/nikosgram/Gringotts/releases/download/2.12.1.1/gringotts-2.12.1.jar

**Comment by LlmDl** [comment]
Progress, it starts and I can place a sign on the chest and receive in chat: Created vault successfully.

About 2 seconds later the sign is popped off and I get in the log: 
`[14:43:11] [Server thread/INFO]: [Gringotts] Destroying orphaned vault: [vault] 106, 4, 121, CraftWorld{name=towny}`

Even before the sign is popped off, my town doesn't have the 23 emeralds in their bank.

This is using the jar from the release page, is the one above any different?

**Comment by LlmDl** [comment]
Apparently doing /town (which queries the bank balance) causes the sign to pop.

**Comment by nikosgram** [comment]
Hmm, for some reason Gringotts thinks that the owner of the sign, in that case the town/nation, is not exists. I'll investigate it a bit further. :)

**Comment by nikosgram** [comment]
Can you try latest version again? :P

https://github.com/nikosgram/Gringotts/releases/download/2.12.1.1/gringotts-2.12.1.jar

In theory, it should be fixed by now.

**Comment by nikosgram** [comment]
Sorry for asking you to try it out, I cannot re-produce the issue.

**Comment by LlmDl** [comment]
That would appear to have solved it. I was able to make the vault, check balance, and upon executing a new day my town bank was charged the appropriate upkeep. I am also able to use /t deposit # and /t withdraw #, so I think that Gringotts is once again working with Towny.

**Comment by nikosgram** [comment]
Lovely to hear. I'll close the ticket now :)

Thank you for testing it out. <3

**Comment by LlmDl** [comment]
Thanks for fixing things up again. People are always asking about gringotts.

**Comment by nikosgram** [comment]
Ah, I know... I just don't have much time to spend on my home projects. I'll try my best to maintain Gringotts on my free time though :)
