### ISSUE TITLE
Error occurred while performing /money

### ISSUE THREAD

**Issue by freeze-dolphin** [nikosgram13/Gringotts#69]
Server Core: Paperspigot 1.12.2
Current Gringotts Version: 2.11.2-SNAPSHOT-rbed0924

I use legacy Gringotts for that the latest release cannot be loaded on 1.12.2

Here is the stack trace, and I would appreciate it if you could help me:
```
[08:54:59 INFO]: Freeze_Dolphin issued server command: /money
[08:54:59 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin Gringotts v2.11.2-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[?:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[?:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at <unknown class>.run(Unknown Source) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:826) [?:1.8.0_312]
Caused by: org.gestern.gringotts.GringottsException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:298) ~[?:?]
        at org.gestern.gringotts.GringottsAccount.getBalance(GringottsAccount.java:80) ~[?:?]
        at org.gestern.gringotts.api.impl.GringottsEco$ValidAccount.balance(GringottsEco.java:473) ~[?:?]
        at org.gestern.gringotts.commands.GringottsAbstractExecutor.sendBalanceMessage(GringottsAbstractExecutor.java:176) ~[?:?]
        at org.gestern.gringotts.commands.MoneyExecutor.onCommand(MoneyExecutor.java:43) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 16 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_312]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) ~[?:1.8.0_312]
        at org.gestern.gringotts.GringottsAccount.getTimeout(GringottsAccount.java:296) ~[?:?]
        at org.gestern.gringotts.GringottsAccount.getBalance(GringottsAccount.java:80) ~[?:?]
        at org.gestern.gringotts.api.impl.GringottsEco$ValidAccount.balance(GringottsEco.java:473) ~[?:?]
        at org.gestern.gringotts.commands.GringottsAbstractExecutor.sendBalanceMessage(GringottsAbstractExecutor.java:176) ~[?:?]
        at org.gestern.gringotts.commands.MoneyExecutor.onCommand(MoneyExecutor.java:43) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 16 more
Caused by: java.lang.NullPointerException
        at java.lang.StackTraceElement.hashCode(StackTraceElement.java:147) ~[?:1.8.0_312]
        at com.avaje.ebean.bean.CallStack.<init>(CallStack.java:52) ~[?:?]
        at com.avaje.ebeaninternal.server.core.DefaultServer.createCallStack(DefaultServer.java:2123) ~[?:?]
        at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryRequest(DefaultServer.java:1137) ~[?:?]
        at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryRequest(DefaultServer.java:1106) ~[?:?]
        at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1512) ~[?:?]
        at com.avaje.ebeaninternal.server.core.DefaultServer.findUnique(DefaultServer.java:1288) ~[?:?]
        at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findUnique(DefaultOrmQuery.java:922) ~[?:?]
        at com.avaje.ebeaninternal.util.DefaultExpressionList.findUnique(DefaultExpressionList.java:193) ~[?:?]
        at org.gestern.gringotts.data.EBeanDAO.retrieveCents(EBeanDAO.java:250) ~[?:?]
        at org.gestern.gringotts.GringottsAccount.lambda$getCents$6(GringottsAccount.java:291) ~[?:?]
        at <unknown class>.get(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_312]
        ... 1 more
> money
[08:55:06 INFO]: [Gringotts] This command can only be run by a player.
[08:55:06 INFO]: /money
[08:55:06 INFO]: /money pay <amount> <player>
```

**Comment by freeze-dolphin** [comment]
Notice that I am on online-mode.

**Comment by nikosgram** [comment]
Hello :)

Does your server includes the Vault plugin? :)

**Comment by freeze-dolphin** [comment]
> Hello :)
> 
> Does your server includes the Vault plugin? :)

I'm sure that I had `Vault-1.7.3` installed. :)

**Comment by nikosgram** [comment]
The Gringotts version you having the issue with is not supported anymore, but, I recommend using the latest version of Gringotts 2.11.2.

Download link: https://github.com/nikosgram/gringotts/releases/download/2.11.2-SNAPSHOT-rf77e523/Gringotts-2.11.2-SNAPSHOT-rf77e523.jar

Let me know if the issue is still there :)

**Comment by GroobleDierne** [comment]
The same issue happened to me today, it does that for all economy calls, on only one specific (and online) player.
May or may not be caused by my latest PR but it seems unlikely as it happens for only one player.
I'm tagging you @nikosgram because this issue is closed and I'm not sure you will see this otherwise.
